import { Metadata } from "next";
import { TeamSection } from "../components/sections/team";

export const metadata: Metadata = {
  title: "About Us Page",
  description: "Generated by create next app",
};

const AboutUs = () => {
  return (
    <>
      <TeamSection />
    </>
  );
};

export default AboutUs;
