import { Metadata } from "next";
import ContactUsForm from "./components/contactusForm";
import { ProducerCompanyDetails } from "../components/ProducerCompanyDetails";
// import { JoinUsSection } from "./components/joinUsSection";

export const metadata: Metadata = {
  title: "Contact US",
  description: "Generated by create next app",
};

const ContactUs = () => {
  return (
    <>
      <ContactUsForm />
      <ProducerCompanyDetails />
      {/* <JoinUsSection /> */}
    </>
  );
};

export default ContactUs;
